app:
  cors:
    allowed-origins:
      - http://localhost:3003
  auth:
    cookie:
      secure: true
      same-site: None

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/milestonemaster_prod}
    username: ${DB_USERNAME:milestonemaster_prod}
    password: ${DB_PASSWORD:milestonemaster_prod}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
    open-in-view: false

logging:
  level:
    com.vikrambhat.milestonemaster: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
