app:
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://localhost:3000

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/milestonemaster}
    username: ${DB_USERNAME:milestonemaster}
    password: ${DB_PASSWORD:milestonemaster}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
