app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:3002
      - http://localhost:5173
      - http://localhost:8082
  auth:
    cookie:
      secure: false
      same-site: Lax

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/milestonemaster_preprod}
    username: ${DB_USERNAME:milestonemaster_preprod}
    password: ${DB_PASSWORD:milestonemaster_preprod}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
    open-in-view: false

logging:
  level:
    com.vikrambhat.milestonemaster: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
